language: php

php:
  - 7.4
  - 7.3
  - 7.2
  - 7.1

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env:
        - xdebug=yes

cache:
  files:
    - .php_cs.cache
  directories:
    - $HOME/.composer/cache

before_script:
  - if [[ "$xdebug" != "yes" ]]; then phpenv config-rm xdebug.ini; fi

install:
  - travis_retry composer install --no-interaction --no-suggest --prefer-dist

script:
  - if [[ "$xdebug" != "yes" ]]; then ./vendor/bin/php-cs-fixer fix --verbose --dry-run --diff --diff-format=udiff --allow-risky=yes; fi
  - if [[ "$xdebug" = "yes" ]]; then ./vendor/bin/phpunit --coverage-php=./build/coverage/phpunit.cov; else ./vendor/bin/phpunit --no-coverage; fi
  - if [[ "$xdebug" = "yes" ]]; then ./vendor/bin/behat --strict; else ./vendor/bin/behat --strict --no-coverage; fi
  - if [[ "$xdebug" = "yes" ]]; then ./vendor/bin/phpcov merge ./build/coverage/ --clover ./build/coverage/coverage.clover; fi
  - if [[ "$xdebug" = "yes" ]]; then ./vendor/bin/php-coveralls --no-interaction -vvv; fi
