language: php

php:
  - 7.4
  - 7.3
  - 7.2
  - 7.1

cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer install --no-interaction --no-suggest --prefer-dist

script:
  - ./vendor/bin/php-cs-fixer fix --verbose --dry-run --diff --diff-format=udiff --allow-risky=yes
  - ./vendor/bin/phpunit
  - ./vendor/bin/behat --strict
